[package]
name = "ssp_backend_types"
version = "0.1.0"
edition.workspace = true

[dependencies]
candid.workspace = true

serde.workspace = true
serde_bytes.workspace = true
serde_cbor.workspace = true

[dev-dependencies]
serde_json.workspace = true
