name: Format and Lint checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/setup-rust
        with:
          cache-key: "fmt"

      - name: Run format command
        run: pnpm format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/setup-rust
        with:
          cache-key: "clippy"

      - name: Run Turborepo lint command
        run: pnpm lint
