name: Unit and Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/setup-rust
        with:
          cache-key: "build-wasm"

      - uses: ./.github/actions/setup-dfx

      - name: Run Turborepo tests
        run: pnpm test
